const fs = require('fs');
const path = require('path');

// Simulate the exact translation pipeline for "Good Morning Students"
console.log('============================================================');
console.log(' REPRODUCING TRANSLATION BUG: "Good Morning Students"');
console.log('============================================================\n');

// 1. Check findSantaliMatch from santaliDataset.ts
const datasetFile = fs.readFileSync('src/data/santaliDataset.ts', 'utf8');

// Load SANTALI_DATASET
// Let's parse Santhali-Words.csv directly to see what row 723 has
const csv = fs.readFileSync('Santhali-Words.csv', 'utf8').split(/\r?\n/).filter(Boolean);
function parseCsvLine(text) {
  const result = [];
  let cur = '';
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const char = text[i];
    if (char === '"') {
      if (inQuotes && text[i + 1] === '"') {
        cur += '"';
        i++;
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === ',' && !inQuotes) {
      result.push(cur.trim());
      cur = '';
    } else {
      cur += char;
    }
  }
  result.push(cur.trim());
  return result;
}

const rows = [];
for (let i = 1; i < csv.length; i++) {
  const cols = parseCsvLine(csv[i]);
  if (cols.length >= 7) {
    rows.push({
      id: cols[0],
      en: cols[3].trim(),
      hi: cols[4].trim(),
      sat: cols[5].trim(),
      roman: cols[6].trim(),
      cat: cols[7]?.trim() || 'Classroom'
    });
  }
}

const input = "Good Morning Students";
const cleanQuery = input.toLowerCase().replace(/[.,!?;:"'()|]/g, '').trim();

// Exact match check
const exactMatch = rows.find(r => r.en.toLowerCase().replace(/[.,!?;:"'()|]/g, '').trim() === cleanQuery);
console.log('1. Exact Dataset Match:');
console.log('   Result:', exactMatch ? `Found Row ${exactMatch.id}` : 'NONE (No exact sentence in dataset)');

// Substring fuzzy match check in findSantaliMatch
console.log('\n2. Fuzzy / Substring Match in findSantaliMatch:');
const substringMatches = rows.filter(r => {
  const normTarget = r.en.toLowerCase().replace(/[.,!?;:"'()|]/g, '').trim();
  return normTarget.includes(cleanQuery) || cleanQuery.includes(normTarget);
});

console.log(`   Found ${substringMatches.length} substring candidates:`);
substringMatches.forEach(m => {
  console.log(`   - Row #${m.id}: "${m.en}"`);
  console.log(`     Santali: "${m.sat}"`);
  console.log(`     Roman  : "${m.roman}"`);
});

// What SantaliDatasetProvider does:
if (substringMatches.length > 0) {
  const best = substringMatches[0];
  const combinedOutput = best.roman ? `${best.sat} (${best.roman})` : best.sat;
  console.log('\n3. Raw Output generated by SantaliDatasetProvider:');
  console.log('   Text:', combinedOutput);
  
  // Check script detection on this raw output
  const hasOlChiki = /[\u1C50-\u1C7F]/.test(combinedOutput);
  const hasLatin = /[a-zA-Z]/.test(combinedOutput);
  console.log('   hasOlChiki:', hasOlChiki);
  console.log('   hasLatin   :', hasLatin);
  console.log('   Detected Script:', hasOlChiki && hasLatin ? 'Mixed (Ol Chiki + Latin)' : hasOlChiki ? 'Ol Chiki' : 'Latin');
}

